name: Update allcnipv6.list

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行（北京时间 8 点）
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}  # 使用存储在 Secrets 中的 PAT

    - name: Fetch and process IPv6 list
      run: |
        curl -s https://ispip.clang.cn/all_cn_ipv6.txt > ipv6.txt
        echo "payload:" > allcnipv6.list
        sed 's/^/  - IP-CIDR6,/' ipv6.txt >> allcnipv6.list
        rm ipv6.txt  # 删除临时文件

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add allcnipv6.list
        git commit -m "Update allcnipv6.list" || echo "No changes to commit"
        git push
