name: Update IP List
on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间00:00(北京时间08:00)运行
  workflow_dispatch: # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Update IP list
      run: python update_script.py

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ipv6-rules.txt
        git commit -m "Update IPv6 rules $(date +'%Y-%m-%d')"
        git push
